global:
  scrape_interval: 15s
scrape_configs:
 - job_name: 'prometheus'
   scrape_interval: 5s

   static_configs:
      - targets: 
        - localhost:9090
        - 192.168.0.121:9100 
        - 192.168.0.121:8889
- job_name: blackbox
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - https://www.robustperception.io/
            - http://prometheus.io/blog
            - http://yourdomain/usage-api/health
            - http://yourdomain/google-apm/health
            - https://google.com            
            - https://www.telegraph.co.uk
            
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 192.168.0.121:9115
