global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']





docker run \
    -p 9090:9090 \
    -v ./:/etc/prometheus \
    prom/prometheus
